### ISSUE TITLE
Directories specified in config file

### ISSUE THREAD

**Issue by chseip** [ApiGen/ApiGen#1029]
Is it possible to specify the directories in the config file?
This means, instead of this:
`vendor/bin/apigen generate src tests --destination docs`
For example to it this way:
```
parameters:
    visibilityLevels: [public, protected] # array
    annotationGroups: [todo, deprecated] # array
    title: "ApiGen Docs" # string
    baseUrl: "http://apigen.org/api" # string
    overwrite: false # bool
    directories: [src, tests]
```
and calling just:
`vendor/bin/apigen generate --destination docs`
