### ISSUE TITLE
Apigen is adding unwanted classes to the Tree

### ISSUE THREAD

**Issue by norberttech** [ApiGen/ApiGen#1106]
Hey! 
I'm trying to generate api docs for https://github.com/flow-php/etl but I'm getting some weird classes in the Tree (project is not using anything from \Ds\ namespace and it's not even in dependencies. 

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/5048a6ff-6a6e-46d2-b94a-dfbf507b9350" />

Here is my config: 

```
parameters:
  title: "Flow PHP - ETL - Api Reference"
  paths: ['%workingDir%/src/core/etl/src']
  include: ['*.php']
  excludeProtected: true
  excludePrivate: true
  excludeTagged: ['internal']
  exclude: ['%workingDir%/vendor/**']
  outputDir: '%workingDir%/web/landing/build/documentation/api/core'
```

I'm keeping it under `src/core/etl/apigen.neon` path in project monorepo https://github.com/flow-php/flow. 

Here is the command I'm using: 

```shell
./tools/apigen/vendor/bin/apigen -c src/core/etl/apigen.neon
 Using Composer autoloader for finding dependencies in /Users/norbert/Workspace/flow-php/flow/vendor.

 Analyzing 480/480 ████████████████████████████ 100% done

 Rendering 1167/1167 ████████████████████████████ 100% done

                                                                                                                        
 [OK] Finished OK                                                                                                                                                                                                                           
```

I assume it's taken somewhere from a dependency of a dependency but even that sounds a bit weird since nothing should bring \Ds as you can see here: https://packagist.org/packages/flow-php/etl#1.x-dev

What I'm missing here or how can I debug it further?
