### ISSUE TITLE
print css

### ISSUE THREAD

**Issue by veka-server** [ApiGen/ApiGen#546]
Hello, 
Can you add this css for remove useless bloc and support a basic print.

```css
@media print { 

	#left, #splitter, #navigation, #search, a.anchor, .short {
		display:none;
	}

	#right {
		margin-left: 0px;
	}

	.detailed {
		display: block;
	}
}
```
Congratulation for this api, it's a good job.

Sorry for my english, i'm french.
