### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by wriver4** [ApiGen/ApiGen#557]
win7 current xampp  1.8.3  PHP: 5.5.6 newest version of apigen, netbeans
xdebug off opcahe off
apigen with debug flag
running from within netbeans
apigen.neon

```yaml
source:
    - Security
destination: c:\xampp\htdocs\DMCIP\Docs
title: DMCIP
charset:
    - UTF-8
exclude: (Archive, Vendor, nbproject)
accessLevels:  (public,  protected,  private)
internal: no
php: no
deprecated: no
tree: no
todo: yes
download: no
sourceCode: no
```

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in phar://C:/xampp/php/apigen.phar/vendor/andrewsville/php-token-reflection/TokenReflection/Broker.php on line 391
