### ISSUE TITLE
How can I pass config values to templates via apigen.neon (like 'googleAnalytics')?

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#626]
```yaml
# apigen.neon
googleAnalytics: UA-123456789-0
anotherValue:    0-987654321
templateColor:   black
```

Then, you can be able to use that values in your `@layout.latte`, same as `googleAnalytics`, to customize the template:

```latte
<script n:if="$config->googleAnalytics">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', {$config->googleAnalytics}]);
		_gaq.push(['_trackPageview']);
```
