### ISSUE TITLE
ApiGen 5 is not using 'apigen.neon' anymore?

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#907]
I have to create a `.yml`?

I was using this [`apigen.neon`](), but seems to not been loading my `themeDirectory`. I just [set to 
an non-existent theme](https://github.com/nelson6e65/php_nml/commit/e6a1ed31bc8eda779a5f07db9e4fae95f50030f2) (to test something about #906 ), but... 

```yaml
parameters:
  # ...
  themeDirectory: "vendor/apigen/apigen/packages/InexistentTheme/src"
```

...is still using the default theme: https://travis-ci.org/nelson6e65/php_nml/builds/248660956#L320
